name: BattleTrainingPlus
main: be.shark_zekrom.Main
version: 0.0.1
api-version: 1.13
description: BattleTrainingPlus
#softdepend: [HolographicDisplays]
commands:
  BattleTraining+:
    description: BattleTraining
